name: prodigy
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: prodigy
      POSTGRES_PASSWORD: prodigy
      POSTGRES_DB: prodigy
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "25234:25234"
    environment:
      - DB_NAME=prodigy
      - DB_USER=prodigy
      - DB_PASS=prodigy
      - DB_HOST=db
      - MIX_ENV=prod
      - SECRET_KEY_BASE=r6ygfUoemC9s6HPcZYwm9EGAC/+Xt6NmcvAidvW7wN2Yd2k3TpuetRZTB5Juvvy0
    depends_on:
      - db
  portal:
    build:
      context: .
      dockerfile: apps/portal/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_NAME=prodigy
      - DB_USER=prodigy
      - DB_PASS=prodigy
      - DB_HOST=db
      - MIX_ENV=prod
      - SECRET_KEY_BASE=r6ygfUoemC9s6HPcZYwm9EGAC/+Xt6NmcvAidvW7wN2Yd2k3TpuetRZTB5Juvvy0
      - GITHUB_CLIENT_ID=identifier
      - GITHUB_CLIENT_SECRET=secret
    depends_on:
      - db

